server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      forwarded:
        enabled: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menus/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/internal/**




internal:
  tokens:
    notification-service: NOTIFICATION_SERVICE_SECRET
    order-service: ORDER_SERVICE_SECRET