server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: Vishal@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user:
  uploads-dir: ./uploads

logging:
  level:
    org.springframework.web: INFO
