server:
  port: 8085
spring:
  application:
    name: menu-service

  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: postgres
    password: Vishal@123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

